name: Generate .deb (ceres)

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker buildx create --use --name devuan-dev --buildkitd-flags '--allow-insecure-entitlement security.insecure'
          docker buildx build --builder devuan-dev -f debian/ceres.dockerfile -t devuan --allow security.insecure --output type=tar,dest=install.tar .

      - name: Extract .deb
        run: |
          # Export it to install
          mkdir install
          sudo tar -C install -psxf install.tar

          # Move content out
          mv install/*.{deb,buildinfo,changes} ./
          mv install/metadata.yml .

          # Clean up
          sudo rm -rf install install.tar

      - name: Set Vars
        id: vars
        run: |
          echo "arch=$(dpkg --print-architecture)" >>"$GITHUB_OUTPUT"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            metadata.yml
            grub-theme-blissos_*_*.buildinfo
            grub-theme-blissos_*_*.changes
            grub-theme-blissos-*_*_*.deb

  release:
    name: Release
    needs: build
    if: ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Download buildfiles
        id: download-buildfiles
        uses: actions/download-artifact@v4
        with:
          path: out
          pattern: "*"
          merge-multiple: true

      - name: List Files
        run: ls -R ${{ steps.download-buildfiles.outputs.download-path }}

      - uses: "softprops/action-gh-release@v2.1.0"
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.download-buildfiles.outputs.download-path }}/*
